// Generated by CoffeeScript 1.9.3
(function() {
  var Score, compare, determineRanks, displayScores, findExisting;

  Score = (function() {
    function Score(name1, points1, rank) {
      this.name = name1;
      this.points = points1;
      this.rank = rank != null ? rank : null;
    }

    return Score;

  })();

  findExisting = function(scores, name) {
    var j, len, score;
    for (j = 0, len = scores.length; j < len; j++) {
      score = scores[j];
      if (score.name === name) {
        return score;
      }
    }
  };

  compare = function(a, b) {
    if (a.points < b.points) {
      return 1;
    }
    if (a.points > b.points) {
      return -1;
    }
    return 0;
  };

  determineRanks = function(scores) {
    var i, results;
    scores[0].rank = 1;
    if (scores.length > 1) {
      i = 1;
      results = [];
      while (i < scores.length) {
        if (scores[i].points === scores[i - 1].points) {
          scores[i].rank = scores[i - 1].rank;
        } else {
          scores[i].rank = scores[i - 1].rank + 1;
        }
        results.push(i++);
      }
      return results;
    }
  };

  displayScores = function(scores) {
    $("#scoreboard").removeClass("hide");
    return $("#rankings").slideUp(300, "swing", function() {
      var j, len, score;
      $("#rankings").empty();
      for (j = 0, len = scores.length; j < len; j++) {
        score = scores[j];
        $("#rankings").append("<li><b>" + score.rank + ".</b> " + score.name + ", " + score.points + " pts.</li>");
      }
      return $("#rankings").slideDown(400, "swing");
    });
  };

  $(function() {
    var scores;
    scores = [];
    $("#add").click(function() {
      var input, name, newScore, player, points;
      if ($(this).hasClass("disabled")) {
        return false;
      } else {
        input = $("input").val().split(",");
        name = input[0];
        points = parseInt(input[1], 10);
        if (findExisting(scores, name)) {
          player = findExisting(scores, name);
          player.points += points;
        } else {
          newScore = new Score(name, points);
          scores.push(newScore);
        }
        $("input").val("");
        $("#add").addClass("disabled");
        scores.sort(compare);
        determineRanks(scores);
        return displayScores(scores);
      }
    });
    $("#clear").click(function() {
      return $("#rankings").slideUp(500, "swing", function() {
        scores.length = 0;
        $("#rankings").empty();
        return $("#scoreboard").addClass("hide");
      });
    });
    return $("input").on('keyup change', function() {
      var valid;
      valid = $("input")[0].validity.valid === true;
      if (valid) {
        return $("#add").removeClass("disabled");
      } else {
        return $("#add").addClass("disabled");
      }
    });
  });

}).call(this);
